# Generated by Django 4.2.2 on 2023-06-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_warranty_alter_supportcase_warranty_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warranty',
            name='product_id',
        ),
    ]
