# Generated by Django 4.2.2 on 2023-06-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_warranty_product_id'),
        ('coverage', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcase',
            name='warranty_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coverage.warranty'),
        ),
        migrations.DeleteModel(
            name='Warranty',
        ),
    ]
